INSERT INTO `gift-certificates`.certificate (id, name, description, price, duration, create_date, last_update_date) VALUES (55, 'ropejumping', 'hellofvfgbdgb', 10.00, 1, '2021-06-11T02:17Z', '2021-06-11T19:57Z');
INSERT INTO `gift-certificates`.certificate (id, name, description, price, duration, create_date, last_update_date) VALUES (56, 'diana', 'mydfvdfvmentor', 2.00, 5, '2021-06-11T02:17Z', '2021-06-11T02:17Z');
INSERT INTO `gift-certificates`.certificate (id, name, description, price, duration, create_date, last_update_date) VALUES (57, 'viktor', 'mydfvdfvmentor', 2.00, 5, '2021-06-11T02:18Z', '2021-06-11T02:18Z');
INSERT INTO `gift-certificates`.certificate (id, name, description, price, duration, create_date, last_update_date) VALUES (59, 'andrewGeniy', 'dasha delaet domashku', 100.00, 10, '2021-06-11T06:15Z', '2021-06-11T13:41Z');
INSERT INTO `gift-certificates`.certificate (id, name, description, price, duration, create_date, last_update_date) VALUES (60, 'relaxspa', 'nicjjjerelax', 200.00, 10, '2021-06-11T19:44Z', '2021-06-11T19:44Z');
INSERT INTO `gift-certificates`.certificate_tags (id, certificate_id, tag_id) VALUES (27, 56, 34);
INSERT INTO `gift-certificates`.certificate_tags (id, certificate_id, tag_id) VALUES (28, 56, 35);
INSERT INTO `gift-certificates`.certificate_tags (id, certificate_id, tag_id) VALUES (29, 56, 36);
INSERT INTO `gift-certificates`.certificate_tags (id, certificate_id, tag_id) VALUES (30, 57, 37);
INSERT INTO `gift-certificates`.certificate_tags (id, certificate_id, tag_id) VALUES (31, 57, 36);
INSERT INTO `gift-certificates`.certificate_tags (id, certificate_id, tag_id) VALUES (72, 59, 45);
INSERT INTO `gift-certificates`.certificate_tags (id, certificate_id, tag_id) VALUES (73, 59, 46);
INSERT INTO `gift-certificates`.certificate_tags (id, certificate_id, tag_id) VALUES (74, 59, 47);
INSERT INTO `gift-certificates`.certificate_tags (id, certificate_id, tag_id) VALUES (75, 59, 48);
INSERT INTO `gift-certificates`.certificate_tags (id, certificate_id, tag_id) VALUES (76, 59, 49);
INSERT INTO `gift-certificates`.certificate_tags (id, certificate_id, tag_id) VALUES (77, 59, 38);
INSERT INTO `gift-certificates`.certificate_tags (id, certificate_id, tag_id) VALUES (80, 60, 41);
INSERT INTO `gift-certificates`.certificate_tags (id, certificate_id, tag_id) VALUES (81, 60, 42);
INSERT INTO `gift-certificates`.certificate_tags (id, certificate_id, tag_id) VALUES (89, 55, 53);
INSERT INTO `gift-certificates`.certificate_tags (id, certificate_id, tag_id) VALUES (90, 55, 54);
INSERT INTO `gift-certificates`.tag (id, name) VALUES (38, 'biology');
INSERT INTO `gift-certificates`.tag (id, name) VALUES (37, 'chemistry');
INSERT INTO `gift-certificates`.tag (id, name) VALUES (41, 'Csharp');
INSERT INTO `gift-certificates`.tag (id, name) VALUES (43, 'dfg');
INSERT INTO `gift-certificates`.tag (id, name) VALUES (49, 'diana');
INSERT INTO `gift-certificates`.tag (id, name) VALUES (44, 'dima');
INSERT INTO `gift-certificates`.tag (id, name) VALUES (42, 'fitness');
INSERT INTO `gift-certificates`.tag (id, name) VALUES (47, 'fresh');
INSERT INTO `gift-certificates`.tag (id, name) VALUES (51, 'fun');
INSERT INTO `gift-certificates`.tag (id, name) VALUES (35, 'gta');
INSERT INTO `gift-certificates`.tag (id, name) VALUES (45, 'insta');
INSERT INTO `gift-certificates`.tag (id, name) VALUES (50, 'lolik');
INSERT INTO `gift-certificates`.tag (id, name) VALUES (34, 'roman');
INSERT INTO `gift-certificates`.tag (id, name) VALUES (36, 'samsung');
INSERT INTO `gift-certificates`.tag (id, name) VALUES (53, 'sdfgh');
INSERT INTO `gift-certificates`.tag (id, name) VALUES (40, 'spat');
INSERT INTO `gift-certificates`.tag (id, name) VALUES (46, 'tiktok');
INSERT INTO `gift-certificates`.tag (id, name) VALUES (52, 'unexisting');
INSERT INTO `gift-certificates`.tag (id, name) VALUES (48, 'year');